global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'publisher'
    static_configs:
      - targets: ['publisher:8000']
  
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']