apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: projekt-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: projekt-balancer
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      scrape_timeout: 1s
    scrape_configs:
      - job_name: 'publisher'
        static_configs:
          - targets: ['publisher:8000']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'kafka-consumer'
        static_configs:
          - targets: ['kafka-consumer:8000']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: projekt-balancer
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32090