apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: projekt-balancer
  labels:
    app: publisher
spec:
  replicas: 4
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: rozyckik/publisher:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  namespace: projekt-balancer
spec:
  type: NodePort
  selector:
    app: publisher
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30090  # <– Wystawi usługę na porcie hosta